name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy CloudFormation Stack
        env:
          AlarmEmail: AlarmEmail@alarm.com
        run: |
          aws cloudformation deploy \
            --stack-name order \
            --template-file cloudformation.yaml \
            --parameter-overrides \
              AlarmEmail=$AlarmEmail \
            --capabilities CAPABILITY_IAM

      - name: Show CloudFormation Stack Outputs
        run: |
          STACK_NAME=order  # Replace with your stack name
          
          # Use AWS CLI to describe stack outputs
          OUTPUTS_JSON=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs' --output json)
          
          # Print the outputs
          echo "CloudFormation Stack Outputs:"
          echo $OUTPUTS_JSON
